version: '3'
services:
  app:
    container_name: estagio_legal_back
    build: .
    environment:
      DB_HOST: database
      DB_PORT: 5432
    depends_on:
      - database
    ports:
      - ${DOCKER_PORT}:${API_PORT}
  database:
    container_name: database_estagio
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: gerenciaAqui
      POSTGRES_USER: gerenciaAqui
      POSTGRES_PASSWORD: gerenciaAqui
    ports:
    - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/database_estagio
  

volumes:
  db_data:
    driver: local
