version: '3'
services:
  app:
    container_name: estagio_legal_back
    build: .
    depends_on:
      - database
    ports:
      - ${DOCKER_PORT}:${API_PORT}
    environment:
      DATABASE_URL: ${DATABASE_URL}
  database:
    container_name: estagio_legal_back_db
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
    - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: